substitutions:
  name: lumentree-inverter
  device_description: "Monitor and control Lumentree solar inverter via BLE"
  external_components_source: github://syssi/esphome-lumentree@main
  mac_address: "AA:BB:CC:DD:EE:FF"  # Replace with your inverter's MAC address

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-lumentree"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome

logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble: DEBUG
    esp32_ble_tracker: INFO
    lumentree_ble: VERY_VERBOSE
    scheduler: INFO
    component: INFO
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO

api:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

ble_client:
  - mac_address: ${mac_address}
    id: client0

lumentree_ble:
  - ble_client_id: client0
    id: inverter0

binary_sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    grid_connected:
      name: "${name} grid connected"
    battery_connected:
      name: "${name} battery connected"

sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    battery_soc:
      name: "${name} battery state of charge"
    ac_voltage:
      name: "${name} ac voltage"
    ac_power:
      name: "${name} ac power"
    pv_voltage:
      name: "${name} pv voltage"
    pv_power:
      name: "${name} pv power"
    grid_power:
      name: "${name} grid power"
    load_power:
      name: "${name} load power"
    device_temperature:
      name: "${name} device temperature"
    pv2_voltage:
      name: "${name} pv2 voltage"
    pv2_power:
      name: "${name} pv2 power"
    device_type_image:
      name: "${name} device type image"
    battery_status:
      name: "${name} battery status"
    grid_connection_status:
      name: "${name} grid connection status"

text_sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    device_model:
      name: "${name} device model"
    operation_mode:
      name: "${name} operation mode"

button:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    factory_reset:
      name: "${name} factory reset"
    restart_device:
      name: "${name} restart device"

number:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    power_output_setting:
      name: "${name} power output setting"
      min_value: 0
      max_value: 2000
      step: 1
      unit_of_measurement: "W"
    equalization_voltage_setting:
      name: "${name} equalization voltage setting"
      min_value: 48.0
      max_value: 60.0
      step: 0.01
      unit_of_measurement: "V"
    charging_target_voltage_setting:
      name: "${name} charging target voltage setting"
      min_value: 48.0
      max_value: 58.0
      step: 0.01
      unit_of_measurement: "V"
    float_charge_voltage_setting:
      name: "${name} float charge voltage setting"
      min_value: 48.0
      max_value: 56.0
      step: 0.01
      unit_of_measurement: "V"
    battery_capacity_setting:
      name: "${name} battery capacity setting"
      min_value: 50
      max_value: 1000
      step: 1
      unit_of_measurement: "Ah"

switch:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    ac_charging:
      name: "${name} ac charging"
    output:
      name: "${name} output"
