substitutions:
  name: lumentree-inverter
  device_description: "Monitor and control Lumentree solar inverter via BLE"
  external_components_source: github://syssi/esphome-lumentree@main
  mac_address: "AA:BB:CC:DD:EE:FF"  # Replace with your inverter's MAC address

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-lumentree"
    version: 1.1.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble: DEBUG
    esp32_ble_tracker: INFO
    lumentree_ble: VERY_VERBOSE
    scheduler: INFO
    component: INFO
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO

api:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

ble_client:
  - mac_address: ${mac_address}
    id: client0

lumentree_ble:
  - ble_client_id: client0
    id: inverter0

binary_sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    grid_connected:
      name: "${name} grid connected"
    battery_connected:
      name: "${name} battery connected"
    pv2_support:
      name: "${name} pv2 support"

sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    battery_soc:
      name: "${name} battery state of charge"
    ac_output_voltage:
      name: "${name} ac output voltage"
    ac_input_voltage:
      name: "${name} ac input voltage"
    ac_output_frequency:
      name: "${name} ac output frequency"
    ac_input_frequency:
      name: "${name} ac input frequency"
    ac_power:
      name: "${name} ac power"
    pv_voltage:
      name: "${name} pv voltage"
    pv_power:
      name: "${name} pv power"
    grid_power:
      name: "${name} grid power"
    load_power:
      name: "${name} load power"
    device_temperature:
      name: "${name} device temperature"
    pv2_voltage:
      name: "${name} pv2 voltage"
    pv2_power:
      name: "${name} pv2 power"
    device_type_image:
      name: "${name} device type image"
    battery_status:
      name: "${name} battery status"
    grid_connection_status:
      name: "${name} grid connection status"
    device_type:
      name: "${name} device type"
    device_power_rating_code:
      name: "${name} device power rating code"
    device_power_rating:
      name: "${name} device power rating"
    ac_output_apparent_power:
      name: "${name} ac output apparent power"
    grid_ct_power:
      name: "${name} grid ct power"
    today_pv_production:
      name: "${name} today pv production"
    today_essential_load:
      name: "${name} today essential load"
    today_total_consumption:
      name: "${name} today total consumption"
    today_grid_consumption:
      name: "${name} today grid consumption"
    today_battery_charging:
      name: "${name} today battery charging"
    today_battery_discharge:
      name: "${name} today battery discharge"
    grid_export:
      name: "${name} grid export"

text_sensor:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    serial_number:
      name: "${name} serial number"
    operation_mode:
      name: "${name} operation mode"
    device_model:
      name: "${name} device model"

select:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    operation_mode:
      name: "${name} operation mode"

switch:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    ac_charging:
      name: "${name} ac charging"
    output:
      name: "${name} output"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"
    id: ble_client_switch0


button:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    battery_settings_reset:
      name: "${name} battery settings reset"

number:
  - platform: lumentree_ble
    lumentree_ble_id: inverter0
    power_output_setting:
      name: "${name} power output setting"
    equalization_voltage_setting:
      name: "${name} equalization voltage setting"
    charging_target_voltage_setting:
      name: "${name} charging target voltage setting"
    float_charge_voltage_setting:
      name: "${name} float charge voltage setting"
    battery_capacity_setting:
      name: "${name} battery capacity setting"
      unit_of_measurement: "Ah"
